### ISSUE TITLE
SSLHandshakeException when trying to use DracoonClient

### ISSUE THREAD

**Issue by wlmim** [dracoon/dracoon-java-sdk#11]
I'm trying to use a `DracoonClient` to download a file using something like:

    client.nodes().downloadFile(uuid, nodeId, tempFile, null);

I'm getting the following stack trace:

```
[HttpHelper] Server SSL handshake failed!

javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131) ~[na:na]
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:378) ~[na:na]
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321) ~[na:na]
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:316) ~[na:na]
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357) ~[na:na]
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232) ~[na:na]
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175) ~[na:na]
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396) ~[na:na]
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480) ~[na:na]
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458) ~[na:na]
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:201) ~[na:na]
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1510) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1425) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426) ~[na:na]
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) ~[okhttp-4.10.0.jar:na]
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154) ~[okhttp-4.10.0.jar:na]
	at com.dracoon.sdk.internal.HttpHelper.executeCall(HttpHelper.java:268) ~[dracoon-sdk-3.1.2.jar:na]
	at com.dracoon.sdk.internal.HttpHelper$NetworkExecutor.execute(HttpHelper.java:239) ~[dracoon-sdk-3.1.2.jar:na]
	at com.dracoon.sdk.internal.HttpHelper$InterceptionErrorHandlingExecutor.execute(HttpHelper.java:139) ~[dracoon-sdk-3.1.2.jar:na]
	at com.dracoon.sdk.internal.HttpHelper.executeRequestInternally(HttpHelper.java:111) ~[dracoon-sdk-3.1.2.jar:na]
	at com.dracoon.sdk.internal.HttpHelper.executeRequest(HttpHelper.java:97) ~[dracoon-sdk-3.1.2.jar:na]
	at com.dracoon.sdk.internal.DownloadStream.requestNextChunk(DownloadStream.java:441) ~[dracoon-sdk-3.1.2.jar:na]
	at com.dracoon.sdk.internal.DownloadStream.downloadData(DownloadStream.java:327) ~[dracoon-sdk-3.1.2.jar:na]
	at com.dracoon.sdk.internal.DownloadStream.read(DownloadStream.java:171) ~[dracoon-sdk-3.1.2.jar:na]
	at java.base/java.io.InputStream.read(InputStream.java:218) ~[na:na]
	at com.dracoon.sdk.internal.DownloadThread.download(DownloadThread.java:83) ~[dracoon-sdk-3.1.2.jar:na]
	at com.dracoon.sdk.internal.DownloadThread.runSync(DownloadThread.java:73) ~[dracoon-sdk-3.1.2.jar:na]
	at com.dracoon.sdk.internal.DracoonNodesImpl.downloadFileInternally(DracoonNodesImpl.java:630) ~[dracoon-sdk-3.1.2.jar:na]
	at com.dracoon.sdk.internal.DracoonNodesImpl.downloadFile(DracoonNodesImpl.java:607) ~[dracoon-sdk-3.1.2.jar:na]
	at MyDracoonService.download(MyDracoonService.java:101) ~[main/:na]
	...
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439) ~[na:na]
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306) ~[na:na]
	at java.base/sun.security.validator.Validator.validate(Validator.java:264) ~[na:na]
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231) ~[na:na]
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132) ~[na:na]
	at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341) ~[na:na]
	... 113 common frames omitted
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:146) ~[na:na]
	at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:127) ~[na:na]
	at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297) ~[na:na]
	at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434) ~[na:na]
	... 118 common frames omitted
```

I'm using `Java 17.0.10` and `dracoon-sdk-3.1.2`.

I'm using a Spring `WebClient` (`org.springframework.web.reactive.function.client.WebClient`) to obtain an accessToken beforehand and this works well on the same Dracoon instance and from the very same running JVM.

So my guess is that it has something to do with the SDK or the used okhttp3 library.

**Comment by wlmim** [comment]
Nevermind: it was our company's "transparent" proxy intercepting download http requests and forcing a manual confirmation page (with technically invalid TLS) in front of them. Access token URLs aren't affected so they went through.

Sorry for the noise.
